// Executive PDF Report Generator — CreditVision AI
// Pure jsPDF drawing for a lender-grade, multi-page report.
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { AssessmentInputs, AssessmentResult, LoanRecommendation } from "./scoring";

type Rgb = [number, number, number];

const C = {
  bg: [15, 19, 33] as Rgb,
  panel: [24, 30, 49] as Rgb,
  panel2: [33, 41, 64] as Rgb,
  border: [54, 65, 92] as Rgb,
  text: [240, 244, 252] as Rgb,
  mute: [156, 169, 197] as Rgb,
  brand: [56, 200, 200] as Rgb,
  brand2: [167, 120, 244] as Rgb,
  success: [60, 195, 130] as Rgb,
  warn: [232, 170, 60] as Rgb,
  danger: [232, 90, 100] as Rgb,
  info: [86, 160, 240] as Rgb,
};

const PAGE_W = 210;
const PAGE_H = 297;
const M = 14; // margin

function setFill(doc: jsPDF, c: Rgb) { doc.setFillColor(c[0], c[1], c[2]); }
function setStroke(doc: jsPDF, c: Rgb) { doc.setDrawColor(c[0], c[1], c[2]); }
function setText(doc: jsPDF, c: Rgb) { doc.setTextColor(c[0], c[1], c[2]); }

function pageFrame(doc: jsPDF, pageNum: number, totalPages: number, applicant: string) {
  // bg
  setFill(doc, C.bg);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
  // header bar
  setFill(doc, C.panel);
  doc.rect(0, 0, PAGE_W, 16, "F");
  setFill(doc, C.brand);
  doc.rect(M, 6, 4, 4, "F");
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("CreditVision AI", M + 7, 9.5);
  doc.setFont("helvetica", "normal").setFontSize(8);
  setText(doc, C.mute);
  doc.text("Alternative Credit Assessment", M + 7, 13);
  doc.text(applicant, PAGE_W - M, 9.5, { align: "right" });
  doc.text(new Date().toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" }), PAGE_W - M, 13, { align: "right" });

  // footer
  setStroke(doc, C.border);
  doc.setLineWidth(0.2);
  doc.line(M, PAGE_H - 12, PAGE_W - M, PAGE_H - 12);
  setText(doc, C.mute);
  doc.setFontSize(7.5);
  doc.text("Confidential — for assessment purposes only. Generated by CreditVision AI.", M, PAGE_H - 7);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - M, PAGE_H - 7, { align: "right" });
}

function sectionTitle(doc: jsPDF, y: number, eyebrow: string, title: string) {
  setText(doc, C.brand);
  doc.setFont("helvetica", "bold").setFontSize(8);
  doc.text(eyebrow.toUpperCase(), M, y);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(16);
  doc.text(title, M, y + 7);
  setStroke(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(M, y + 10, PAGE_W - M, y + 10);
}

function panel(doc: jsPDF, x: number, y: number, w: number, h: number) {
  setFill(doc, C.panel);
  setStroke(doc, C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");
}

function statBlock(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string, valueColor: Rgb = C.text) {
  panel(doc, x, y, w, h);
  setText(doc, C.mute);
  doc.setFont("helvetica", "normal").setFontSize(8);
  doc.text(label.toUpperCase(), x + 5, y + 7);
  setText(doc, valueColor);
  doc.setFont("helvetica", "bold").setFontSize(20);
  doc.text(value, x + 5, y + h - 5);
}

function progressBar(doc: jsPDF, x: number, y: number, w: number, pct: number, color: Rgb) {
  setFill(doc, C.panel2);
  doc.roundedRect(x, y, w, 2.5, 1, 1, "F");
  setFill(doc, color);
  const fw = Math.max(0, Math.min(100, pct)) / 100 * w;
  if (fw > 0) doc.roundedRect(x, y, fw, 2.5, 1, 1, "F");
}

function riskColor(level: string): Rgb {
  if (level === "Low") return C.success;
  if (level === "Moderate") return C.info;
  if (level === "Elevated") return C.warn;
  return C.danger;
}
function eligColor(s: string): Rgb {
  if (s === "Approved") return C.success;
  if (s === "Conditional Approval") return C.info;
  if (s === "Manual Review") return C.warn;
  return C.danger;
}

// ---------- Pages ----------

function pageCover(doc: jsPDF, r: AssessmentResult, applicant: string) {
  // Hero
  panel(doc, M, 26, PAGE_W - 2 * M, 110);

  // Big score dial
  const cx = M + 50, cy = 80, R = 32;
  setStroke(doc, C.panel2);
  doc.setLineWidth(6);
  doc.circle(cx, cy, R, "S");
  // arc using line segments
  setStroke(doc, C.brand);
  doc.setLineWidth(6);
  const steps = 64;
  const frac = Math.max(0, Math.min(100, r.overallScore)) / 100;
  let prevX = cx, prevY = cy - R;
  for (let i = 1; i <= Math.round(steps * frac); i++) {
    const a = -Math.PI / 2 + (i / steps) * 2 * Math.PI;
    const nx = cx + R * Math.cos(a);
    const ny = cy + R * Math.sin(a);
    doc.line(prevX, prevY, nx, ny);
    prevX = nx; prevY = ny;
  }
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(28);
  doc.text(String(Math.round(r.overallScore)), cx, cy + 2, { align: "center" });
  setText(doc, C.mute);
  doc.setFont("helvetica", "normal").setFontSize(7);
  doc.text("OVERALL SCORE", cx, cy + 9, { align: "center" });

  // Right: applicant + meta
  const rx = M + 100;
  setText(doc, C.mute);
  doc.setFont("helvetica", "normal").setFontSize(8);
  doc.text("APPLICANT", rx, 40);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(20);
  doc.text(applicant || "Applicant", rx, 50);

  setText(doc, C.mute);
  doc.setFontSize(8);
  doc.text("ASSESSMENT DATE", rx, 62);
  setText(doc, C.text);
  doc.setFont("helvetica", "normal").setFontSize(11);
  doc.text(new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" }), rx, 69);

  setText(doc, C.mute);
  doc.setFontSize(8);
  doc.text("REPORT ID", rx, 79);
  setText(doc, C.text);
  doc.setFont("courier", "normal").setFontSize(10);
  doc.text("CV-" + Date.now().toString(36).toUpperCase(), rx, 86);

  // Status pills
  const pillY = 110;
  drawPill(doc, M + 8, pillY, "Risk: " + r.riskLevel, riskColor(r.riskLevel));
  drawPill(doc, M + 60, pillY, r.eligibilityStatus, eligColor(r.eligibilityStatus));
  drawPill(doc, M + 122, pillY, "Confidence: " + Math.round(r.confidenceScore) + "%", C.brand2);

  // Three KPI cards
  const ky = 146, kw = (PAGE_W - 2 * M - 8) / 3, kh = 30;
  statBlock(doc, M, ky, kw, kh, "Overall Score", String(Math.round(r.overallScore)) + " / 100", C.brand);
  statBlock(doc, M + kw + 4, ky, kw, kh, "Risk Level", r.riskLevel, riskColor(r.riskLevel));
  statBlock(doc, M + 2 * (kw + 4), ky, kw, kh, "Confidence", Math.round(r.confidenceScore) + "%", C.brand2);

  // Category snapshot
  const sy = 186;
  panel(doc, M, sy, PAGE_W - 2 * M, 86);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("Category Snapshot", M + 6, sy + 8);
  const rowH = 10;
  r.categories.forEach((c, i) => {
    const ry = sy + 16 + i * rowH;
    setText(doc, C.text);
    doc.setFont("helvetica", "normal").setFontSize(9);
    doc.text(c.label, M + 6, ry + 4);
    setText(doc, C.mute);
    doc.setFontSize(7.5);
    doc.text(c.weight + "% weight", M + 70, ry + 4);
    progressBar(doc, M + 95, ry + 2, 70, c.score, C.brand);
    setText(doc, C.text);
    doc.setFont("helvetica", "bold").setFontSize(9);
    doc.text(String(Math.round(c.score)), PAGE_W - M - 6, ry + 4, { align: "right" });
  });
}

function drawPill(doc: jsPDF, x: number, y: number, text: string, color: Rgb) {
  const w = doc.getTextWidth(text) + 10;
  setFill(doc, [color[0], color[1], color[2]]);
  doc.roundedRect(x, y - 5, w, 7.5, 3.5, 3.5, "F");
  setText(doc, [255, 255, 255]);
  doc.setFont("helvetica", "bold").setFontSize(8);
  doc.text(text, x + w / 2, y, { align: "center" });
}

function pageSummary(doc: jsPDF, r: AssessmentResult, applicant: string) {
  sectionTitle(doc, 26, "Section 1", "Executive Summary");

  const intro =
    `${applicant || "The applicant"} has been evaluated by CreditVision AI's alternative credit ` +
    `assessment engine using six independent factors covering financial stability, banking behaviour, ` +
    `employment quality, behavioural discipline, education, and bill payment consistency. The ` +
    `assessment is based entirely on inputs provided and behavioural signals — not on traditional ` +
    `credit history.`;

  panel(doc, M, 38, PAGE_W - 2 * M, 36);
  setText(doc, C.text);
  doc.setFont("helvetica", "normal").setFontSize(9.5);
  const lines = doc.splitTextToSize(intro, PAGE_W - 2 * M - 12);
  doc.text(lines, M + 6, 46);

  // AI Assessment Summary
  let y = 84;
  sectionTitle(doc, y, "Section 2", "AI Assessment Summary");
  y += 16;
  panel(doc, M, y, PAGE_W - 2 * M, 70);
  const bullets: string[] = [];
  bullets.push(`Overall score of ${Math.round(r.overallScore)}/100 indicates a ${r.riskLevel.toLowerCase()} risk profile.`);
  bullets.push(`Confidence of ${Math.round(r.confidenceScore)}% reflects the depth of data available for evaluation.`);
  if (r.strengths.length) bullets.push(`Top strength: ${r.strengths[0]}`);
  if (r.concerns.length) bullets.push(`Key concern: ${r.concerns[0]}`);
  if (r.missingInformation.length) bullets.push(`Missing: ${r.missingInformation.slice(0, 2).join("; ")}. Providing this would raise confidence.`);
  r.insights.slice(0, 2).forEach(s => bullets.push(s));

  let by = y + 8;
  bullets.forEach(b => {
    setFill(doc, C.brand);
    doc.circle(M + 6, by - 1, 0.9, "F");
    setText(doc, C.text);
    doc.setFont("helvetica", "normal").setFontSize(9.5);
    const ls = doc.splitTextToSize(b, PAGE_W - 2 * M - 16);
    doc.text(ls, M + 10, by);
    by += ls.length * 5 + 2;
  });

  // Final Recommendation
  y = 168;
  sectionTitle(doc, y, "Section 3", "Final Recommendation");
  y += 16;
  panel(doc, M, y, PAGE_W - 2 * M, 80);

  setText(doc, C.mute);
  doc.setFont("helvetica", "bold").setFontSize(8);
  doc.text("UNDERWRITING DECISION", M + 6, y + 9);
  setText(doc, eligColor(r.eligibilityStatus));
  doc.setFont("helvetica", "bold").setFontSize(22);
  doc.text(r.eligibilityStatus, M + 6, y + 22);

  setText(doc, C.text);
  doc.setFont("helvetica", "normal").setFontSize(9.5);
  const rec =
    r.eligibilityStatus === "Approved" ? "The profile meets capacity and behaviour thresholds. Recommended for standard onboarding."
    : r.eligibilityStatus === "Conditional Approval" ? "Approve with conditions — request additional verification (income proof / bank statement) before disbursement."
    : r.eligibilityStatus === "Manual Review" ? "Refer to a human underwriter. Score is acceptable but confidence is limited by missing data."
    : "Decline at this time — repayment capacity cannot be established from provided inputs.";
  const recLines = doc.splitTextToSize(rec, PAGE_W - 2 * M - 12);
  doc.text(recLines, M + 6, y + 34);

  setText(doc, C.mute);
  doc.setFont("helvetica", "bold").setFontSize(8);
  doc.text("PHILOSOPHY", M + 6, y + 60);
  setText(doc, C.text);
  doc.setFont("helvetica", "italic").setFontSize(9);
  doc.text("No credit history is treated as missing information, not as risk. Confidence — not score — is reduced when data is unavailable.", M + 6, y + 67, { maxWidth: PAGE_W - 2 * M - 12 });
}

function drawRadar(doc: jsPDF, cx: number, cy: number, R: number, labels: string[], values: number[]) {
  const n = labels.length;
  // grid
  setStroke(doc, C.border);
  doc.setLineWidth(0.2);
  for (let g = 1; g <= 4; g++) {
    const r = (R * g) / 4;
    const pts: [number, number][] = [];
    for (let i = 0; i < n; i++) {
      const a = -Math.PI / 2 + (i / n) * 2 * Math.PI;
      pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
    }
    for (let i = 0; i < n; i++) {
      const [x1, y1] = pts[i];
      const [x2, y2] = pts[(i + 1) % n];
      doc.line(x1, y1, x2, y2);
    }
  }
  // spokes
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i / n) * 2 * Math.PI;
    doc.line(cx, cy, cx + R * Math.cos(a), cy + R * Math.sin(a));
  }
  // data polygon
  const pts: [number, number][] = [];
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i / n) * 2 * Math.PI;
    const r = R * (values[i] / 100);
    pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
  }
  setStroke(doc, C.brand);
  doc.setLineWidth(0.8);
  setFill(doc, C.brand);
  doc.setGState(new (doc as any).GState({ opacity: 0.25 }));
  // polygon fill via triangles from center
  for (let i = 0; i < n; i++) {
    const [x1, y1] = pts[i];
    const [x2, y2] = pts[(i + 1) % n];
    doc.triangle(cx, cy, x1, y1, x2, y2, "F");
  }
  doc.setGState(new (doc as any).GState({ opacity: 1 }));
  // outline
  for (let i = 0; i < n; i++) {
    const [x1, y1] = pts[i];
    const [x2, y2] = pts[(i + 1) % n];
    doc.line(x1, y1, x2, y2);
  }
  // labels
  setText(doc, C.text);
  doc.setFont("helvetica", "normal").setFontSize(7.5);
  for (let i = 0; i < n; i++) {
    const a = -Math.PI / 2 + (i / n) * 2 * Math.PI;
    const lx = cx + (R + 8) * Math.cos(a);
    const ly = cy + (R + 8) * Math.sin(a) + 1;
    const align = Math.cos(a) > 0.2 ? "left" : Math.cos(a) < -0.2 ? "right" : "center";
    doc.text(labels[i], lx, ly, { align: align as any });
  }
}

function pageCharts(doc: jsPDF, r: AssessmentResult) {
  sectionTitle(doc, 26, "Section 4", "Score & Risk Breakdown");

  // Radar
  panel(doc, M, 40, (PAGE_W - 2 * M - 4) / 2, 100);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(10);
  doc.text("Six-Factor Radar", M + 6, 48);
  drawRadar(doc, M + 45, 92, 32,
    r.categories.map(c => c.label.split(" ")[0]),
    r.categories.map(c => c.score));

  // Risk + Confidence bars
  const rx = M + (PAGE_W - 2 * M) / 2 + 2;
  panel(doc, rx, 40, (PAGE_W - 2 * M - 4) / 2, 100);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(10);
  doc.text("Risk Index & Confidence", rx + 6, 48);

  const risk = 100 - r.overallScore;
  setText(doc, C.mute);
  doc.setFont("helvetica", "normal").setFontSize(8);
  doc.text("RISK INDEX (lower is better)", rx + 6, 58);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(14);
  doc.text(Math.round(risk) + " / 100", rx + 6, 67);
  progressBar(doc, rx + 6, 71, 80, risk, risk < 30 ? C.success : risk < 55 ? C.info : risk < 70 ? C.warn : C.danger);

  doc.setFont("helvetica", "normal").setFontSize(8);
  setText(doc, C.mute);
  doc.text("CONFIDENCE", rx + 6, 86);
  setText(doc, C.text);
  doc.setFont("helvetica", "bold").setFontSize(14);
  doc.text(Math.round(r.confidenceScore) + "%", rx + 6, 95);
  progressBar(doc, rx + 6, 99, 80, r.confidenceScore, C.brand2);

  setText(doc, C.mute);
  doc.setFont("helvetica", "italic").setFontSize(7.5);
  doc.text("Risk and confidence are reported independently. Missing data\nlowers confidence — not your risk score.", rx + 6, 115);

  // Category bars
  let y = 150;
  sectionTitle(doc, y, "Section 5", "Category Scores");
  y += 16;
  panel(doc, M, y, PAGE_W - 2 * M, 96);
  const rowH = 14;
  r.categories.forEach((c, i) => {
    const ry = y + 8 + i * rowH;
    setText(doc, C.text);
    doc.setFont("helvetica", "bold").setFontSize(9);
    doc.text(c.label, M + 6, ry + 4);
    setText(doc, C.mute);
    doc.setFont("helvetica", "normal").setFontSize(7.5);
    doc.text("Weight " + c.weight + "%", M + 6, ry + 9);

    progressBar(doc, M + 70, ry + 2, 90, c.score, C.brand);
    progressBar(doc, M + 70, ry + 7, 90, c.confidence, C.brand2);

    setText(doc, C.text);
    doc.setFont("helvetica", "bold").setFontSize(10);
    doc.text(Math.round(c.score) + "", M + 168, ry + 4);
    setText(doc, C.brand2);
    doc.setFont("helvetica", "normal").setFontSize(8);
    doc.text(Math.round(c.confidence) + "%", M + 168, ry + 9);
  });
}

function pageContributors(doc: jsPDF, r: AssessmentResult) {
  sectionTitle(doc, 26, "Section 6", "Explainable AI — Score Contributors");

  const blockH = 80;
  const bw = PAGE_W - 2 * M;

  // Positive
  panel(doc, M, 40, bw, blockH);
  setText(doc, C.success);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("+  Positive Contributors", M + 6, 48);
  drawList(doc, r.strengths, M + 6, 54, bw - 12, C.success, "+", "No standout positive signals detected from current inputs.");

  // Risk
  panel(doc, M, 40 + blockH + 6, bw, blockH);
  setText(doc, C.warn);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("!  Risk Contributors", M + 6, 48 + blockH + 6);
  drawList(doc, r.concerns, M + 6, 54 + blockH + 6, bw - 12, C.warn, "-", "No active risk signals flagged.");

  // Missing
  panel(doc, M, 40 + 2 * (blockH + 6), bw, blockH);
  setText(doc, C.info);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("?  Missing Information (not counted as risk)", M + 6, 48 + 2 * (blockH + 6));
  drawList(doc, r.missingInformation, M + 6, 54 + 2 * (blockH + 6), bw - 12, C.info, "?", "Profile is fully populated.");
}

function drawList(doc: jsPDF, items: string[], x: number, y: number, w: number, color: Rgb, glyph: string, empty: string) {
  if (items.length === 0) {
    setText(doc, C.mute);
    doc.setFont("helvetica", "italic").setFontSize(9);
    doc.text(empty, x, y + 6);
    return;
  }
  let cy = y + 6;
  items.slice(0, 6).forEach(it => {
    setText(doc, color);
    doc.setFont("helvetica", "bold").setFontSize(9);
    doc.text(glyph, x, cy);
    setText(doc, C.text);
    doc.setFont("helvetica", "normal").setFontSize(9);
    const ls = doc.splitTextToSize(it, w - 8);
    doc.text(ls, x + 5, cy);
    cy += ls.length * 4.5 + 2;
  });
}

function pageRecommendations(doc: jsPDF, r: AssessmentResult) {
  sectionTitle(doc, 26, "Section 7", "Lending Recommendations");

  setText(doc, C.mute);
  doc.setFont("helvetica", "italic").setFontSize(8.5);
  doc.text("All amounts, interest ranges, and probabilities are derived from the assessment inputs — none are hard-coded.",
    M, 42, { maxWidth: PAGE_W - 2 * M });

  autoTable(doc, {
    startY: 50,
    head: [["Product", "Eligibility", "Recommended Amount", "Interest Range", "Approval"]],
    body: r.recommendations.map(rec => [
      rec.product,
      rec.eligible ? "Eligible" : "Not Eligible",
      rec.eligible ? "₹" + rec.recommendedAmount.toLocaleString("en-IN") : "—",
      rec.interestRange[1] > 0 ? rec.interestRange[0] + "–" + rec.interestRange[1] + "%" : "—",
      rec.approvalProbability + "%",
    ]),
    theme: "grid",
    styles: { fillColor: C.panel as any, textColor: C.text as any, lineColor: C.border as any, lineWidth: 0.2, fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: C.brand as any, textColor: [12, 18, 30] as any, fontStyle: "bold" },
    alternateRowStyles: { fillColor: C.panel2 as any },
    margin: { left: M, right: M },
  });

  // Rationale cards
  let y = (doc as any).lastAutoTable.finalY + 8;
  r.recommendations.forEach(rec => {
    if (y > PAGE_H - 40) return;
    panel(doc, M, y, PAGE_W - 2 * M, 24);
    setText(doc, C.text);
    doc.setFont("helvetica", "bold").setFontSize(10);
    doc.text(rec.product, M + 5, y + 7);
    setText(doc, rec.eligible ? C.success : C.danger);
    doc.setFontSize(8);
    doc.text(rec.eligible ? "ELIGIBLE" : "NOT ELIGIBLE", PAGE_W - M - 5, y + 7, { align: "right" });
    setText(doc, C.mute);
    doc.setFont("helvetica", "normal").setFontSize(8.5);
    const ls = doc.splitTextToSize(rec.rationale, PAGE_W - 2 * M - 12);
    doc.text(ls, M + 5, y + 13);
    y += 28;
  });
}

function deriveRoadmap(r: AssessmentResult, i: AssessmentInputs): { actions: string[]; suggestions: string[] } {
  const actions: string[] = [];
  const suggestions: string[] = [];

  if (i.emergencyFundMonths < 3) actions.push(`Build an emergency fund of at least ${Math.max(3, 6)} months of expenses (currently ${i.emergencyFundMonths} months).`);
  if (i.monthlyIncome > 0 && (i.monthlyIncome - i.monthlyExpenses) / i.monthlyIncome < 0.2) actions.push("Increase monthly surplus to 20%+ of income by reducing discretionary expenses.");
  if (i.avgBankBalance < i.monthlyExpenses) actions.push("Maintain an average bank balance equal to or above one month of expenses.");
  if (i.overdraftEvents > 0) actions.push("Eliminate overdraft events by setting up low-balance alerts and auto-transfers.");
  if (i.failedTransactions > 3) actions.push("Reduce failed transactions — they signal liquidity stress to underwriters.");
  if (i.jobTenureMonths < 12 && !["student", "fresher", "unemployed"].includes(i.employmentType)) actions.push("Sustain current employment for 12+ months to strengthen tenure signal.");
  if (i.certifications < 2) actions.push("Add 1–2 professional certifications to strengthen human-capital score.");

  if (r.missingInformation.includes("Bank transaction history")) suggestions.push("Connect or upload 6 months of bank statements — projected confidence +12–18%.");
  if (r.missingInformation.includes("Verified monthly income")) suggestions.push("Provide salary slips or income proof — projected confidence +10–15%.");
  if (r.missingInformation.includes("Bill payment history")) suggestions.push("Add utility / telecom / rent payment records — projected score +4–7.");
  if (r.missingInformation.includes("Established employment history")) suggestions.push("Once 6+ months of employment data is available, score moves from potential-based to capacity-based.");
  if (i.digitalPaymentUsage < 4) suggestions.push("Increase digital payment usage — projected behavioural score +5–8.");
  if (i.transactionConsistency < 4) suggestions.push("Maintain consistent monthly inflows/outflows — projected score +3–6.");

  if (actions.length === 0) actions.push("Profile is well-balanced — maintain current discipline.");
  if (suggestions.length === 0) suggestions.push("Profile data is comprehensive. Continue regular activity to keep signals fresh.");
  return { actions, suggestions };
}

function pageRoadmap(doc: jsPDF, r: AssessmentResult, i: AssessmentInputs) {
  sectionTitle(doc, 26, "Section 8", "Improvement Roadmap");

  const { actions, suggestions } = deriveRoadmap(r, i);

  // Recommended actions
  panel(doc, M, 42, PAGE_W - 2 * M, 110);
  setText(doc, C.brand);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("Recommended Actions", M + 6, 50);
  setText(doc, C.mute);
  doc.setFont("helvetica", "italic").setFontSize(8);
  doc.text("Concrete steps derived from your current profile.", M + 6, 55);

  let y = 62;
  actions.slice(0, 8).forEach((a, idx) => {
    setFill(doc, C.brand);
    doc.circle(M + 8, y - 1, 2.5, "F");
    setText(doc, [12, 18, 30]);
    doc.setFont("helvetica", "bold").setFontSize(8);
    doc.text(String(idx + 1), M + 8, y + 0.8, { align: "center" });
    setText(doc, C.text);
    doc.setFont("helvetica", "normal").setFontSize(9);
    const ls = doc.splitTextToSize(a, PAGE_W - 2 * M - 24);
    doc.text(ls, M + 14, y);
    y += ls.length * 4.5 + 4;
  });

  // Score improvement suggestions
  const y2 = 162;
  panel(doc, M, y2, PAGE_W - 2 * M, 100);
  setText(doc, C.brand2);
  doc.setFont("helvetica", "bold").setFontSize(11);
  doc.text("Score & Confidence Improvement", M + 6, y2 + 8);
  setText(doc, C.mute);
  doc.setFont("helvetica", "italic").setFontSize(8);
  doc.text("Each suggestion is mapped to its projected impact on your profile.", M + 6, y2 + 13);

  let yy = y2 + 20;
  suggestions.slice(0, 7).forEach(s => {
    setFill(doc, C.brand2);
    doc.roundedRect(M + 6, yy - 3, 3, 3, 0.5, 0.5, "F");
    setText(doc, C.text);
    doc.setFont("helvetica", "normal").setFontSize(9);
    const ls = doc.splitTextToSize(s, PAGE_W - 2 * M - 18);
    doc.text(ls, M + 12, yy);
    yy += ls.length * 4.5 + 3;
  });
}

// ---------- Entry ----------
export function generatePdfReport(opts: {
  applicantName: string;
  inputs: AssessmentInputs;
  result: AssessmentResult;
}): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const applicant = opts.applicantName || opts.inputs.name || "Applicant";

  const pages = [
    () => pageCover(doc, opts.result, applicant),
    () => pageSummary(doc, opts.result, applicant),
    () => pageCharts(doc, opts.result),
    () => pageContributors(doc, opts.result),
    () => pageRecommendations(doc, opts.result),
    () => pageRoadmap(doc, opts.result, opts.inputs),
  ];

  pages.forEach((render, idx) => {
    if (idx > 0) doc.addPage();
    pageFrame(doc, idx + 1, pages.length, applicant);
    render();
  });

  return doc;
}

export function downloadPdfReport(opts: Parameters<typeof generatePdfReport>[0]) {
  const doc = generatePdfReport(opts);
  const safe = (opts.applicantName || "applicant").replace(/[^a-z0-9]+/gi, "_");
  doc.save(`CreditVision_Report_${safe}_${Date.now()}.pdf`);
}
